name: mm4cc-pkg
services:
  ppa-host:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./site-root:/usr/share/nginx/html:ro
  tunnel:
    image: cloudflare/cloudflared
    env_file: .tunnel.env
    command: tunnel run
  indexer:
    build: ./indexer
    volumes:
      - ./site-root:/srv/site-root
      - ./indexer:/home/indexer
